//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyVersionAttribute("2.1.0.0")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.1.28.17358")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.1.28-preview+ce43a16900")]
#if NETSTANDARD || NETFRAMEWORK || NETCOREAPP
[System.CodeDom.Compiler.GeneratedCode("Nerdbank.GitVersioning.Tasks","3.0.28.11123")]
#endif
internal static partial class ThisAssembly {
    internal const string AssemblyVersion = "2.1.0.0";
    internal const string AssemblyFileVersion = "2.1.28.17358";
    internal const string AssemblyInformationalVersion = "2.1.28-preview+ce43a16900";
    internal const string AssemblyName = "Unity.VersionControl.Git";
    internal const string AssemblyTitle = "Unity.VersionControl.Git";
    internal const string AssemblyConfiguration = "Release";
    internal const string GitCommitId = "ce43a169005ab11cebc63ae635bb99a9eea0594c";
    internal static readonly System.DateTime GitCommitDate = new System.DateTime(637353677020000000L, System.DateTimeKind.Utc);
    internal const string RootNamespace = "Git";
}
