public enum BoneTypes
{
    GenericBonePile,
    SlimePile,
    CrypterBonePile,
    DisposedCondom,
    CumPuddle,
    CrypterSkull,
    HumanoidSkull,
    LizardSkull,
    Imp2EyeSkull,
    Imp1EyeSkull,
    Imp3EyeSkull,
    SeliciaSkull,
    FurryBones,
    FurryRabbitBones,
    HarrysGooPile,
    Kangaroo,
    Alligator,
    Wyvern,
    Compy,
    Shark,
    DarkSwallower,
    Cake,
    WyvernBonesWithoutHead,
    VisionSkull,
    HoneyPuddle,

}

