public enum SpellTypes
{
    None = 0,
    Fireball = 1,
    PowerBolt = 2,
    LightningBolt = 3,
    Shield = 4,
    Mending = 5,
    Speed = 6,
    Valor = 7,
    Predation = 8,

    IceBlast = 9,
    Pyre = 10,
    //Warp,
    //MagicWall,
    Poison = 11,

    //Quicksand,
    PreysCurse = 12,
    Maw = 13,
    Charm = 14,
    Summon = 15,
    Reanimate = 16,
    Enlarge = 17,

    //Raze,
    Diminishment = 18,
    GateMaw = 19,
    ViralInfection = 20,
    DivinitysEmbrace = 21,

    Resurrection = 22,

    AmplifyMagic = 23,
    Evocation = 24,
    ManaFlux = 25,
    UnstableMana = 26,
    Meditate = 27,
    Bloodrite = 28,
    Protect = 29,

    ForcePulse = 35,
    Trance = 36,
    FlameWave = 37,
    SummonDoppelganger = 38,
    FireBomb = 39,
    Bolas = 40,
    SummonSpawn = 41,
    CaptureNet = 42,
    Icicle = 43,
    CrossShock = 44,
    JoltCrash = 45,
    ArcBolt = 46,
    PreysHex = 47,

    AlraunePuff = 70,
    Web = 71,
    GlueBomb = 72,
    ViperPoison = 73,
    Petrify = 74,
    HypnoGas = 75,
    Bind = 76,
    Whispers = 77,
    //Corrupt = 78,
    ExplosiveHug = 79,

    ViperDamage = 110,
    ForceFeed = 111,
    AssumeForm = 112,
    RevertForm = 113,
    ManaExpolsion = 114,
    Conduit = 115,
    Flamberge = 116,
    ForkLightning = 117,
    Explode = 118,
    SweepingSwallow = 119,
}

